---
- name: Reload daemons
  shell: systemctl daemon-reload

- name: restart rabbitmq
  service:
    name: rabbitmq-server
    state: restarted

- name: restart rabbitmq_exporter
  service:
    name: rabbitmq_exporter
    state: restarted
